baseURL = "http://ethique.xyz/"
languageCode = "fr-fr"
title = "Éthique minimale"
theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 50

preserveTaxonomyNames = true

[params]
  description = "Une éthique applicable qui tient en un tweet"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "CC-BY-SA 4.0 Ethique.xyz"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = true
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = true
  showReadTime = true

[author.social]
  twitter = ""

# Language Configuration
defaultContentLanguage = "fr"

[languages]
  # edit this block for your own language
  [languages.fr]
    lang = "fr"
    languageName = "Français"
    weight = 1
