# For theme relative config, see below
archetypeDir =                "archetypes"
# hostname (and path) to the root, e.g. http://spf13.com/
baseURL = "https://ethique.xyz"
# include content marked as draft
buildDrafts =                 false
# include content with publishdate in the future
buildFuture =                 false
# include content already expired
buildExpired =                false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs =                false
canonifyURLs =                true
# config file (default is path/config.yaml|json|toml)
config =                     "config.toml"
contentDir =                  "content"
dataDir =                     "data"
defaultExtension =            "html"
defaultLayout =               "post"
# Missing translations will default to this content language
defaultContentLanguage =      "fr"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir =  false
disableLiveReload =           false
# Enable GitInfo feature
enableGitInfo =               false
# Build robots.txt file
enableRobotsTXT =             true
# Do not render 404 page
disableHugoGeneratorInject =  false
# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds = []
# Do not make the url/path to lowercase
disablePathToLower =          false
# Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
enableEmoji =                 false
# Show a placeholder instead of the default value or an empty string if a translation is missing
enableMissingTranslationPlaceholders = false
footnoteAnchorPrefix =        ""
footnoteReturnLinkContents =  "&larrhk;"
# google analytics tracking id
googleAnalytics =             ""
# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage =              false
languageCode =                ""
# the length of text to show in a .Summary
summaryLength =              70
layoutDir =                   "layouts"
# Enable Logging
log =                         false
# Log File path (if set, logging enabled automatically)
logFile =                     ""
# maximum number of items in the RSS feed
rssLimit =                    15
# "toml","yaml", or "json"
metaDataFormat =              "toml"
newContentEditor =            ""
# Don't sync permission mode of files
noChmod =                     false
# Don't sync modification time of files
noTimes =                     false
# Pagination
paginate =                    10
paginatePath =                "page"
# See "content-management/permalinks"
permalinks =                  ""
# Pluralize titles in lists using inflect
pluralizeListTitles =         true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames =       true # set by Minimo
# filesystem path to write files to
publishDir =                  "public"
# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax = false
# color-codes for highlighting derived from this style
pygmentsStyle =               "monokai"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses =          false
# see "Section Menu for Lazy Bloggers", /templates/menu-templates for more info
SectionPagesMenu =            ""
# default sitemap configuration map
sitemap =                     ""
# filesystem path to read static files relative from
staticDir =                   "static"
# display memory and timing of different steps of the program
stepAnalysis =                false
# theme to use (located by default in /themes/THEMENAME/)
themesDir =                   "themes"
theme =                       "minimo"
#title =                       "Éthique minimale"
# if true, use /filename.html instead of /filename/
uglyURLs =                    false
# verbose output
verbose =                     false
# verbose logging
verboseLog =                  false
# watch filesystem for changes and recreate as needed
watch =                       true

## Minimo theme more specific confif

# for smart copyright line, leave this blank and check [params.copyright]
copyright =                   ""
disqusShortname =             ""
# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences =          true

#[params.info]
#description = "Une éthique applicable qui tient en un tweet"
#title404 = "404 !"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "CC-BY-SA 4.0 Ethique.xyz"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page", "blog"] # boolean / array of sections
recentPostsLength = 10
hideSocialMenu = true
showReadingTime = true

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = ""
facebook = ""
github = ""
instagram = ""
linkedin = ""
twitter = ""

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

# [permalinks]
# page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.fr]
lang = "fr"
languageName = "Français"
weight = 1
title = "Éthique minimale"

[languages.fr.params.info]
description = "Une éthique applicable qui tient en un tweet"

[[languages.fr.menu.main]]
url    = "/"
name   = "Accueil"
weight = 5
[[languages.fr.menu.main]]
url    = "/page/a-propos"
name   = "À propos"
weight = 10
[[languages.fr.menu.main]]
url    = "/page/faq"
name   = "F.A.Q"
weight = 20
[[languages.fr.menu.main]]
name = "🇬🇧"
weight = 30
url = "/en/"

[languages.en]
lang = "en"
languageName = "English"
weight = 1
title= "Ruwen Ogien's Miminal Ethics"

[languages.en.params.info]
description = "A usable ethics that fits it a tweet"

[[languages.en.menu.main]]
url    = "/en/"
name   = "Home"
weight = 5
[[languages.en.menu.main]]
url    = "/en/page/a-propos"
name   = "About"
weight = 10
[[languages.en.menu.main]]
url    = "/en/page/faq"
name   = "F.A.Q"
weight = 20
[[languages.en.menu.main]]
name = "🇫🇷"
weight = 30
url = "/"
